---
- hosts: myhosts
  connection: local
  name: set web session timeout
  gather_facts: False

# web_session_timeout: The timeout of a web session in minutes, The value range is 5-480.

  tasks:
  - name: set web session timeout
    ibmc_set_web_session_timeout :
      ibmc_ip: "{{ ibmc_ip }}"
      ibmc_user: "{{ ibmc_user }}"
      ibmc_pswd: "{{ ibmc_pswd }}"
      web_session_timeout: 420
